# Generated by Django 2.0.9 on 2018-12-17 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocaccounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='icon',
            field=models.CharField(choices=[('person', 'Person'), ('shop', 'Shop'), ('persons', 'Club'), ('suitcase', 'Cash'), ('home', 'Bank')], default='person', max_length=12),
        ),
    ]
