# Generated by Django 2.0.9 on 2018-12-15 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ocaccounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date Issued')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ocaccounts.Project')),
            ],
        ),
        migrations.AddField(
            model_name='charge',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ocaccounts.Invoice'),
        ),
    ]
