# Generated by Django 2.0.9 on 2018-12-15 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocaccounts', '0002_auto_20181215_1604'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='entity',
            options={'verbose_name_plural': 'Entities'},
        ),
        migrations.AddField(
            model_name='entity',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=12),
            preserve_default=False,
        ),
    ]
