# Generated by Django 2.0.9 on 2018-12-17 12:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ocaccounts', '0002_auto_20181217_1111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='date',
            new_name='dateRaised',
        ),
        migrations.RemoveField(
            model_name='charge',
            name='date',
        ),
        migrations.AddField(
            model_name='charge',
            name='dateMade',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date Made'),
            preserve_default=False,
        ),
    ]
