# Generated by Django 2.0.9 on 2018-12-17 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ocaccounts', '0003_auto_20181217_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charge',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='source_set', to='ocaccounts.Entity'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='sink',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sink_set', to='ocaccounts.Entity'),
        ),
    ]
