# Generated by Django 2.0.9 on 2018-12-17 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ocaccounts', '0005_charge_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='charge',
            old_name='Category',
            new_name='category',
        ),
    ]
