# Generated by Django 2.0.9 on 2018-12-17 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ocaccounts', '0006_auto_20181217_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charge',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ocaccounts.Category'),
        ),
    ]
