# Generated by Django 2.0.9 on 2018-12-18 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocaccounts', '0007_auto_20181217_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='charge',
            name='gift',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='charge',
            name='description',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
