# Generated by Django 2.0.9 on 2019-01-13 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocaccounts', '0008_auto_20181218_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='fixed',
            field=models.BooleanField(default=False),
        ),
    ]
